DROP TABLE IF EXISTS comments CASCADE;
DROP TABLE IF EXISTS thumbs CASCADE;
DROP TABLE IF EXISTS blog_details CASCADE;
DROP TABLE IF EXISTS followers CASCADE;
DROP TABLE IF EXISTS bloggers CASCADE;
DROP TABLE IF EXISTS blogs CASCADE;
DROP TABLE IF EXISTS blog_types;
DROP TABLE IF EXISTS images; 